blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/Tyler887/Hello-World/discussions/categories/discussions
    about: Please uss discussions to ask questions
    button: Discussions
