blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/Tyler887/Hello-World/discussions/categories/discussions
    about: Ask a question about this
  - name: New language
    about: Request a new language
    url: https://github.com/Tyler887/Hello-World/compare
